name: Lint code with pycodestyle

on:
  push:
    branches:
      - '*'  # Monitorowanie wszystkich gałęzi
  pull_request:
    branches:
      - '*'

jobs:
  lint-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pycodestyle
      run: pip install pycodestyle
    - name: Run pycodestyle
      run: pycodestyle . --max-line-length=79

  lint-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pycodestyle
      run: pip install pycodestyle
    - name: Run pycodestyle
      run: pycodestyle . --max-line-length=79

  lint-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pycodestyle
      run: pip install pycodestyle
    - name: Run pycodestyle
      run: pycodestyle . --max-line-length=79
